Implement basic RSO modules loader
Cuyler36/Ghidra-GameCube-Loader pull request #51
Opened 2022-01-06 17:26 UTC by InusualZ

Basic Implementation for loading [RSO Modules](http://www.metroid2002.com/retromodding/wiki/RSO_(File_Format)). The loader only support loading the file on his own. Not linking against any other module (or `dol`)

There are a few questionable decision (like the `switch` table for naming the sections). But for the most part it works.

Also, I used some of the code from @Cuyler36 `rso` branch.

Please test this, I only have one game that uses this kind modules (MHTri), but I know that other games utilize them.

2022-01-07 21:08 UTC, Cuyler36 requested changes
Looks good at first glance, but as you pointed out that switch statement isn't great. Maybe create a class for holding properties like name + read/write/execute and add them to an array? The RSO section layout is likely standard (no promises), and I feel like a lookup table would be much cleaner than the giant switch block.

2022-01-07 21:08 UTC, Cuyler36 commented on src/main/java/gamecubeloader/rso/RSOProgramBuilder.java
> +					switch (s) {
Looks good at first glance, but as you pointed out that switch statement isn't great. Maybe create a class for holding properties like name + read/write/execute and add them to an array? The RSO section layout is likely standard (no promises), and I feel like a lookup table would be much cleaner than the giant switch block.

2022-01-08 02:29 UTC, InusualZ commented
I decided to use an `enum`. What do you think?

2022-01-10 03:37 UTC, Cuyler36 commented
Much better, enum is probably preferred here. Thanks for your work on this, I had intended to finish it but you saved me the trouble.

2022-01-10 03:37 UTC, merged