Fix REL section loading
Cuyler36/Ghidra-GameCube-Loader pull request #81
Opened 2024-01-01 17:54 UTC by vabold

As a consequence of this, the initial memory address now refers to the start of the REL header, not the start of the first section.

The address of the BSS section can now be manually specified to match the expectation of OSLink.

Credit to Seeky for writing the initial patch for Ghidra 10.1.

2024-01-02 18:20 UTC, Cuyler36 requested changes

2024-01-02 18:20 UTC, Cuyler36 commented on src/main/java/gamecubeloader/rel/RELProgramBuilder.java
> +								relInfo.reader.getByteProvider().getInputStream(offs), section.size, "", null, true, true, isText, null, this.monitor);
Something around here breaks symbol map loading in AC. The symbol map loader code may need to be modified to account for these changes.

2024-06-14 16:25 UTC, vabold commented on src/main/java/gamecubeloader/rel/RELProgramBuilder.java
> +								relInfo.reader.getByteProvider().getInputStream(offs), section.size, "", null, true, true, isText, null, this.monitor);
Fixed in 9fd1a4f.

2024-06-15 06:52 UTC, Cuyler36 requested changes

2024-06-15 06:52 UTC, Cuyler36 commented on src/main/java/gamecubeloader/rel/RELHeader.java
> +		return this.size() + (int) this.sectionCount * 8;
This line is broken. It should be `return this.Size() + (int) this.sectionCount * 8;`. Capitalizing Size method name should resolve it.

2024-06-15 13:09 UTC, vabold commented on src/main/java/gamecubeloader/rel/RELHeader.java
> +		return this.size() + (int) this.sectionCount * 8;
Fixed in cf62696.

2024-06-15 18:13 UTC, merged

2024-06-15 18:14 UTC, Cuyler36 commented
It might be worth it to revisit this in the future to add a toggle option on whether to include the REL headers. Additionally, it might be nice to mark the header sections 'RelocatableModuleHeader_ZZZ' or something alike.